### ISSUE TITLE
MediaConch Ubuntu packages for 15.04 and 15.10 reference a package that doesn't exist

### ISSUE THREAD

**Issue by mistydemeo** [MediaArea/MediaConch_SourceCode#119]
The [Ubuntu packages](https://mediaarea.net/MediaConch/downloads/ubuntu.html) for MediaConch's libmediainfo0v5 express a dependency on libtinyxml2-0.0.0; however, that package is no longer distributed under that name since trusty. vivid and wily have packages for libtinyxml2-2v5 (2.2.0) and libtinyxml2.6.2v5 (2.6.2).

**Comment by JeromeMartinez** [comment]
Oops, we build our own version of libtinyxml2 because [OBS](https://build.opensuse.org/) does not have Universe, and we missed this change. Weird that nobody complained sooner!

**Comment by JeromeMartinez** [comment]
[libtinyxml2-2v5 is in the OBS repo](https://build.opensuse.org/package/binaries/home:MediaArea_net/libtinyxml2_u15.10?repository=xUbuntu_15.10), so the modification was not missed, but the linker (during build of libmediainfo) did something wrong (linking to old package name), we are tracking the bug now.

**Comment by JeromeMartinez** [comment]
Workaround for 14.10 and 15.04: I replaced libmediainfo by v0.7.80 (the previous one), the previous version was actually working well. The behavior is OK (just missing the FFV1 parser name in the Matroska trace)
15.10 had no 0.7.80 package, so disabled for the moment.

**Comment by GuillaumeRoques** [comment]
The build have been fixed and files have been updated on the website, you can download them again.

**Comment by mistydemeo** [comment]
Can confirm - the new versions work fine! Thanks for the rapid response!
