### ISSUE TITLE
New Ubuntu icon is small

### ISSUE THREAD

**Issue by JeromeMartinez** [MediaArea/MediaConch_SourceCode#120]
Tested with Ubuntu 15.04:

MediaConch 15.11:
![15 11](https://cloud.githubusercontent.com/assets/1641638/12102117/03275520-b339-11e5-83d9-05333f4de79b.png)

MediaConch 15.12:
![15 12](https://cloud.githubusercontent.com/assets/1641638/12102122/091ff572-b339-11e5-8f2d-06af8a185f69.png)

The expected behavior is the one from 15.11 (same size as other icons)
Note: reboot after each install, else the icon is the one cached by the operating system.

**Comment by tribouille** [comment]
Done for next snapshots/releases...
https://github.com/MediaArea/MediaConch_SourceCode/pull/130
