### ISSUE TITLE
MediaTrace xml output is invalid

### ISSUE THREAD

**Issue by dericed** [MediaArea/MediaConch_SourceCode#133]
If mediatrace is used alone the output is invalid (no <MediaTrace> node).

```mediaconch -mt file.mov``` makes invalid xml

but when used with mediainfo/mediaarea it is ok:
```mediaconch -mi -mt -fx file.mov``` works

**Comment by tribouille** [comment]
Hmmm :)

For XML output, it is mediaconch -mt -fx file.mov

The commnd you provided is for Text output...
And for text output with MediaTrace... It's due to MediaInfoLib (Option before parsing...) or waiting for the XSL to have Text from MediaTrace XML :)

**Comment by JeromeMartinez** [comment]
@tribouille , is mediaconch -mt -fx file.mov OK?

**Comment by dericed** [comment]
```mediaconch -mt -fx file.mov``` works

**Comment by dericed** [comment]
But mediaconch doesn't yet support text output for mediatrace. Broken xml doesn't count as text output. @ablwr is there a text display for mediatrace?

**Comment by ablwr** [comment]
Nope. When it emerges, is it fine if it lives in this folder: https://github.com/MediaArea/MediaConch_SourceCode/tree/master/Source/Resource/displays as MediaTraceText.xsl? Right now only MediaConch is there. Dunno where MediaInfo text output pulls from.

**Comment by tribouille** [comment]
MediaInfo Text comes from MediaInfoLib (as the previous MediaTrace Text came from until we stopped to analyze the file X times).

If you put it in Resource/displays, it will appear in the display list (used by implementation report et policy report...)... Not really a good idea :)

**Comment by ablwr** [comment]
Where should a MediaTraceText.xsl live?

**Comment by ablwr** [comment]
I pushed some (very basic) XSL to the main repo for now. Needs to be optimized into template with recursive loop and style added. But for now:
Text: https://github.com/MediaArea/MediaConch/blob/master/MetadataDevelopment/Displays/TextOutput/MediaTraceText.xsl
HTML: https://github.com/MediaArea/MediaConch/blob/master/MetadataDevelopment/Displays/HTMLOutput/MediaTrace.xsl

**Comment by tribouille** [comment]
MC repository is ok for now.
Ok, I'll use them.
Tell me when you update them, I'll update in MC_SC.

**Comment by tribouille** [comment]
There it is: https://github.com/MediaArea/MediaConch_SourceCode/pull/142

**Comment by tribouille** [comment]
Should be corrected in snapshots (using Ashley's XSL).
