### ISSUE TITLE
mediatrace jstree view clips data

### ISSUE THREAD

**Issue by dericed** [MediaArea/MediaConch_SourceCode#135]
For a sample file see test2.mkv in http://sourceforge.net/projects/matroska/files/test_files/matroska_test_w1_1.zip/download.

When test2.mkv is loaded into MediaTrace it has a TagString which equals `Matroska Validation File 2, 100,000 timecode scale, odd aspect ratio, and CRC-32. Codecs are AVC and AAC`; however in the display only `Matroska Validation File 2, 100,000 time` is visible.

I propose that we need some ui to allow a longer value to expand upon some interaction (double clicking on value box?).

**Comment by GuillaumeRoques** [comment]
It has been fixed with this https://github.com/MediaArea/MediaConch/issues/99 :)
Column have no more predefined width size, they will scale automatically with the content (if content is too large there is an horizontal scrollbar)
You can test it on MediaConchOnline
