### ISSUE TITLE
mediatrace with a line break within <data> breaks jstree

### ISSUE THREAD

**Issue by dericed** [MediaArea/MediaConch_SourceCode#139]
Here is a fragment of MediaTrace from the attached file:
```xml
<block offset="984730" name="TagString" info="I / LOVE
LINE BREAKS" size="21">
    <block offset="984730" name="Header" size="3">
        <data offset="984730" name="Name">1159</data>
        <data offset="984732" name="Size">18</data>
    </block>
    <data offset="984733" name="Data">I
LOVE
LINE BREAKS</data>
</block>
```
In the GUI, the json tree for both MediaInfo and MediaTrace is blank. Downloading the xml from the GUI works appropriately.

[test1multilinetag.mkv.zip](https://github.com/MediaArea/MediaConch_SourceCode/files/86647/test1multilinetag.mkv.zip)

I made this test file to test if multi-line values are accessible with the JSTree GUI (re: https://github.com/MediaArea/MediaConch_SourceCode/issues/135) but couldn't get that far.

**Comment by tribouille** [comment]
https://github.com/MediaArea/MediaConch_SourceCode/pull/141

Multi-lines become a one-line with JS-Tree-Grid.

**Comment by tribouille** [comment]
Should be corrected in snapshots.
