### ISSUE TITLE
GUI for Mac OS X - repeat issue "Not Valid" with only one rule that is true for diff. files

### ISSUE THREAD

**Issue by foundscapes** [MediaArea/MediaConch_SourceCode#179]
Set up test policy in GUI (NC - Audio Test) w/ only one rule for the audio file:
"Format is MPEG Audio" - checked an mp3 that I'd run via the CLI with output = Format: MPEG Audio. Set rule to: Type: Audio, Field: Format, Occurrence: -1, Validator: is_equal, Value; MPEG Audio

Same thing happened > 3 times with an .avi video file and only one rule.

**Comment by tribouille** [comment]
Wrong trace generated:
For instance: "</block info="V 4" info2="q 2">".
Which makes the MA impossible to be created.
