### ISSUE TITLE
Declare default verbosity level

### ISSUE THREAD

**Issue by pjotrek-b** [MediaArea/MediaConch_SourceCode#261]
Currently, I don't find any way of knowing/seeing what the "Default" value for verbosity is set to.

Would it be possible to remove the "Default" entry - and simply add the word to the number it relates to?

**Example:**

> 1 (Default)

Might in general also be used for declaring what is minimum/maximum.
For example:

> 0 (No messages)
> 1 (Default)
> 2
> 3 
> 4
> 5 (Debug level)

**Comment by pjotrek-b** [comment]
Oh! I just saw that in the Results / Implementation report, the verbosity level is declared:

> Default (5)

But then this is missing on the other parts in the GUI where verbosity is displayed (e.g. Checker).

**Comment by tribouille** [comment]
Hi,

Default in the checker means the one defined in the settings.
Default in the settings means 5.
Default in the implementation results means 5.

**Comment by tribouille** [comment]
I close it because it changes in the last release:

settings: default can be a number or last verbosity used.
checker: select the default value, so, no default label.

Wording of number is more related to issue #259.
