### ISSUE TITLE
Settings persistance frustrations

### ISSUE THREAD

**Issue by pjotrek-b** [MediaArea/MediaConch_SourceCode#262]
Choosing file inconsistency: 

 1. When you check a local file and click on checker and choose a file, MediaConch always puts you in the home folder, not previous folder we were in. So I always have to go through choose path again - tedious :disappointed:

 2. Choosing policy/anything: 
After filling out dialogue & choosing file: When checking next file, I have to set everything again :weary:

 3. Would be great to change it so that while application is running, it remembers its settings

 4. Icing on the cake:
Having MediaConch remember its settings (previous folder, policy, display, verbosity, etc) even if restarted :innocent:

**Comment by tribouille** [comment]
Hi,

(see #263 for more information)

1. Done in 16.04

2. Save report is done, I'll do it for policy/display.

3. Yep

4. Done for what is done :)

I let you try the 16.04.
(Design of the settings will change to graphical)

**Comment by tribouille** [comment]
Policy and display also available: https://github.com/MediaArea/MediaConch_SourceCode/pull/265
Available from tomorrow snapshots or in the next release (16.05)
