### ISSUE TITLE
Improve HTML display output

### ISSUE THREAD

**Issue by ablwr** [MediaArea/MediaConch_SourceCode#273]
@JeromeMartinez, @pjotrek-b, anyone else:

This weekend I want to work on improving the HTML display. Can you let me know what I should focus on? The main complaint I see from Jérôme is that the vertical should be condensed. 

I also hear it's a little too verbose, but sounds like that will be on hold until we integrate verbosity levels a little better (or, because of the way the XSL works or checking each node, that will take care of the verbosity in the report at the same time).

**Comment by JeromeMartinez** [comment]
my main concern is about having only few results per "page". 
It is not about verbosity by MC itself, e.g. we can have a condensed display and user can click on the test and more details are displayed.

Header: 
"MediaConch report" takes lot of vertical space.
Policy name is OK (useful), having the description by default is too verbose, user should see only the name and should have a method for seeing the description (tooltip, click...)

For each test:
4 lines with 3 of them in big letters and vertical space between each line.
Should be condensed in 1 line per test, with normal size of characters, with e.g. test name + trackid + outcome", and when user clicks on the test it is expanded with test description, tracktype, tracktypeorder, trackid, context field, context value, actual, outcome, reason (as now)
Example of condensed result (should be with column alignment):

<pre>
avc1 video: #1 ❌ fail
Minimum Video Bitrate 3.5Mbps: #1 ❌ fail  
Audio is 48kHz: #2 ✅ pass  
Audio is 48kHz: #3 ❌ fail  
</pre>

then click on each line would show more details about the test.

**Comment by ablwr** [comment]
Thanks! Didn't realize the month had slipped away so quickly -- will work on this tonight.

**Comment by ablwr** [comment]
I can go further in moving to the one-line as you have above but clicking on the test to expand the results in-line would require a little bit of javascript too. This works for MCO but will it then work inside of the GUI?

**Comment by JeromeMartinez** [comment]
JavaScript is fine for MC too.

**Comment by GuillaumeRoques** [comment]
JS is ok but without external dependency (no jquery/bootstrap) to be able to work without internet access (for MC and when user download the report).
It should be also working with CSS3, e.g. :
http://callmenick.com/post/css-toggle-switch-examples
http://stackoverflow.com/questions/21919044/css3-transition-on-click-using-pure-css#21919261

**Comment by ablwr** [comment]
Oh! And we're using 3 in both? I'll go for a pure CSS approach first, does that sound the best for you, @GuillaumeRoques? I want to keep it as simple as possible for these three use cases (MCO, GUI, downloaded/offline/stored).

**Comment by GuillaumeRoques** [comment]
CSS support depend on the browser (it should work for IE >= 9 but need to be tested) : 
http://www.w3schools.com/cssref/css3_browsersupport.asp

**Comment by ablwr** [comment]
This is why I've deferred to the JS method in the past. Sorry I've been so short on time -- I'll see what we can sort out.

**Comment by JeromeMartinez** [comment]
1st part of the improvement in the just release v16.05.

**Comment by ablwr** [comment]
#326 should resolve
