### ISSUE TITLE
XSL Policy for General Conformance XSL doesn't exist

### ISSUE THREAD

**Issue by dinahhandel** [MediaArea/MediaConch_SourceCode#329]
As noted in https://github.com/MediaArea/MediaConch-Website/issues/20 the XSL Policy for General Conformance doesn't exist, so it can't be downloaded. When the user clicks on the link, it is a 404 page. Is it possible to get this policy so that the link can be fixed?

**Comment by dericed** [comment]
I don't think it's worth it. It was a very early demo of a policy which was removed because of its quality. I think we should remove the link to it, rather than resurrect it.

**Comment by dinahhandel** [comment]
Should the entire demo be removed in that case?

**Comment by ablwr** [comment]
If the demo is as far out of date as I think it is, we should remove the whole thing until we make one that works.

**Comment by tribouille** [comment]
I will remove the files in MediaConch_SourceCode with the XSL updates.
Please, do not do it before (That makes conflicts... and the policy rework is kind of huge so lot of conflicts...). This new policy system should be available for the next next release (august).

So, except if you need to have an update for the end of the month, please, wait.
(And, they still provide some policies examples (the one in the GUI in "System policy") until it i not changed)

**Comment by ablwr** [comment]
I believe this issue relates to the MediaConch-Website repo and doesn't have anything to do with the source code in the GUI or WUI. That's why I closed it this morning. Plus I'm afraid of deleting things in the SourceCode!
