### ISSUE TITLE
internal error for parsing Policy in Testing_Multiple_Files.xsl

### ISSUE THREAD

**Issue by dinahhandel** [MediaArea/MediaConch_SourceCode#330]
When I tried to test multiple files using the demo's instructions, I received the following error message: 

Dinahs-MacBook-Air:~ dinahhandel$ mediaconch -mc Testing Multiple Files_1.mkv Testing Multiple Files_2.mkv Testing Multiple Files_3.mkv -p Testing_Multiple_Files.xsl
internal error for parsing Policy

Entity: line 85: parser error : Opening and ending tag mismatch: policyChecks line 14 and media

          </media>

                  ^

Entity: line 86: parser error : Opening and ending tag mismatch: media line 10 and xsl:for-each

        </xsl:for-each>

                      ^

Entity: line 87: parser error : Opening and ending tag mismatch: for-each line 9 and policyChecks

      </policyChecks>

                    ^

Here is the Testing_Multiple_Files.xsl : https://gist.github.com/dinahhandel/145b5c8e9f8018c5645fd2c15ec1e6ac

**Comment by JeromeMartinez** [comment]
@tribouille do you concatenate something in text or is it only XSLT processing?

**Comment by dinahhandel** [comment]
Here's the actual xsl file: https://github.com/MediaArea/MediaConch_SourceCode/blob/master/Source/Resource/policies/Testing_Multiple_Files.xsl

**Comment by tribouille** [comment]
The error is coming from the policy XSL.
If you check with xmllint, it will show the XML error.
To make it works, you have to put the "</policyChecks>" line 87 before "</media>" line 85.

```
xmllint Testing_Multiple_Files.xsl 
Testing_Multiple_Files.xsl:85: parser error : Opening and ending tag mismatch: policyChecks line 14 and media
          </media>
                  ^
Testing_Multiple_Files.xsl:86: parser error : Opening and ending tag mismatch: media line 10 and xsl:for-each
        </xsl:for-each>
                       ^
Testing_Multiple_Files.xsl:87: parser error : Opening and ending tag mismatch: for-each line 9 and policyChecks
      </policyChecks>
                     ^
```

**Comment by ablwr** [comment]
Similar to https://github.com/MediaArea/MediaConch_SourceCode/issues/329, I vote to remove demo which has been out of date even at its creation. Especially with the forthcoming policy updates.

**Comment by tribouille** [comment]
I corrected it at the beginning of the month... To make it compatible with the new GUI policy but not the new policy.
I close this one, decision on #329 .
