### ISSUE TITLE
setting value in a policy's rule does not save

### ISSUE THREAD

**Issue by dericed** [MediaArea/MediaConch_SourceCode#336]
To re-create, create a new rule:
Type = Video
Field = FrameRate
Occurrence = 1
Value = 10.000

leave rule and return, the value is now removed. This happens in many scenarios, for instance if I try to make a rule to say that the DisplayAspectRatio should be greater than or equal to 1.500, the value will not save.

**Comment by tribouille** [comment]
https://github.com/MediaArea/MediaConch_SourceCode/pull/338
