### ISSUE TITLE
GUI: UX: Policy deletion requires "exit" of alert message

### ISSUE THREAD

**Issue by ablwr** [MediaArea/MediaConch_SourceCode#353]
Saw a UX error in the GUI only. When deleting a rule within a policy, an alert/notification message is raised. This error must be X'ed out in order to proceed appropriately. Since it was not required, a user can continue to try to use the software but then it becomes distorted until this is resolved/unlocked. The expected behavior is that when a user clicks away from a policy deletion/edit/etc, it should clear the notification message.

Because I have a larger screen, it doesn't affect my user experience. But smaller screens will cause the editor on the right to drop below view (until deletion/confirmation alert is closed).

Was working with a recent nightly build (from within the past 3 days).

**Comment by ablwr** [comment]
Here is an example 
<img width="1072" alt="screen shot 2016-07-24 at 9 15 19 am" src="https://cloud.githubusercontent.com/assets/3260492/17082695/35e9fb22-517f-11e6-86f7-472614325bc4.png">

**Comment by tribouille** [comment]
Same for MCO, same code :)
(maybe this notifcation is not present for some actions in MCO, added on GUI to know what I am doing..).
Anyway, a timer for notification can be added.

**Comment by ablwr** [comment]
It's present in MCO but it's not a problem because the browser knows how to make a lil more room when the DOM is manipulated.... or maybe I have only tested on non-tiny monitors.

**Comment by GuillaumeRoques** [comment]
This have been fixed, the message is removed when user click on another policy/rule and the message do not change the height of the column.
