### ISSUE TITLE
 v16.07 GUI # Cannot exit GUI using Ctr+Q or Esc

### ISSUE THREAD

**Issue by beyo-ra** [MediaArea/MediaConch_SourceCode#366]
Running on Linux using Awesome Windows Manager.

Request/ śuggestion: the GUI should support exit using at least one shortcut command.

**Comment by GuillaumeRoques** [comment]
Thanks, we will take a look at it

**Comment by tribouille** [comment]
https://github.com/MediaArea/MediaConch_SourceCode/pull/372

**Comment by JeromeMartinez** [comment]
> at least one shortcut command.

There was already the classic Alt-F4.
Ctrl-Q is added.
Not fan of Esc, less common nowadays (more used for escaping from a window in a program rather than the program itself).
