### ISSUE TITLE
 v16.07 GUI # Manually removing items have no effect between sessions?

### ISSUE THREAD

**Issue by beyo-ra** [MediaArea/MediaConch_SourceCode#369]
Removing an item from the "Results" column manually only temporarily removes the item from the cokumn. The column is reset when
- switching to and back from another tab, such as "Policies" or "Settings",
- restarting the program.

The problem does not occur when using "Close all results".

**Comment by GuillaumeRoques** [comment]
Thanks, I confirm the bug. This have been fixed in #371
