### ISSUE TITLE
 v16.07 GUI # "Choose Files" cannot handle ampersand (&)?

### ISSUE THREAD

**Issue by beyo-ra** [MediaArea/MediaConch_SourceCode#370]
The file "Hippo & Dog.mpg" results in "No valid"; Implementation report:
- "Validation generated an internal error"

The same file renamed "HippoDog.mpg" results in "Valid"; Implementation report:
- IS_EBML Results: ✅
Results: n/a (Reason: Not recognized as an FFV1 format but as MPEG-PS) 
Name: mi:Format
Value: MPEG-PS

- IS_FFV1 Results: ✅
Results: n/a (Reason: Not recognized as an FFV1 format but as MPEG Video) 
Name: mi:Format
Value: MPEG Video

**Comment by GuillaumeRoques** [comment]
Thanks, I confirm the bug, it's not working on GUI/CLI/Server.

**Comment by tribouille** [comment]
https://github.com/MediaArea/MediaConch_SourceCode/pull/373
