### ISSUE TITLE
Add file name containing "%" and "&" to Travis

### ISSUE THREAD

**Issue by JeromeMartinez** [MediaArea/MediaConch_SourceCode#374]
add test for avoiding a regression from 
https://github.com/MediaArea/MediaConch_SourceCode/pull/373

**Comment by JeromeMartinez** [comment]
"%" was GUI only, maybe difficult to automate.

**Comment by tribouille** [comment]
There are also filename with:
* <
* >
* '
* "

**Comment by tribouille** [comment]
https://github.com/MediaArea/MediaConch_SourceCode/pull/390
