### ISSUE TITLE
sort by policy in checker doesn't change sort

### ISSUE THREAD

**Issue by dericed** [MediaArea/MediaConch_SourceCode#408]
When I click on the sort in the policy column, there appears to be no change, the order is the same. The sort on implementation is okay with all Not Valid first then Valid, but for the Policy column it only shows the select policy name, so there is nothing meaningful to sort on.

**Comment by JeromeMartinez** [comment]
Select file 1 with policy 1, "check"
Select file 2 with policy 2, "check"
then you can sort by policy name (and sort by policy in checker does change sort).

Not the expected behavior?

**Comment by JeromeMartinez** [comment]
Should we sort policies by valid / not valid?

**Comment by dericed** [comment]
I see your point. I think I expected:

```
policy1 : fail
policy1 : pass
policy2 : fail
policy2 : pass
```

or 

```
fail: policy1
fail: policy2
pass: policy1
pass: policy2
```

**Comment by JeromeMartinez** [comment]
I vote for:

```
policy1 : fail
policy1 : pass
policy2 : fail
policy2 : pass
```

**Comment by dericed** [comment]
Partial answer, but I vote that sort matches implementation checker.

```
invalid: DPX1
invalid: MKV1
valid: DPX2
valid: MKV2
```

**Comment by JeromeMartinez** [comment]
we need coherency.
What is the first sorting field? valid/invalid or policy_name/implementation_name?

Currently we don't have the implementation_name, so more complex.
What happens if both MKV and FFV1 are invalid?

**Comment by dericed** [comment]
To add more confusion, what is MKV is valid and FFV1 inside is invalid? O_O

**Comment by JeromeMartinez** [comment]
so let's go for:

```
invalid: DPX1
invalid: MKV1
valid: DPX2
valid: MKV2
```
 (format is future)

and

```
fail: policy1
fail: policy2
pass: policy1
pass: policy2
```

**Comment by GuillaumeRoques** [comment]
FYI ordering is made on the textual content of the fields.
I added an hidden text in the policy field to match your criteria, you can test it in the test instance.
