### ISSUE TITLE
Migrate from Exist to Must Exist

### ISSUE THREAD

**Issue by JeromeMartinez** [MediaArea/MediaConch_SourceCode#446]
in the GUI, I have "Exists" and "Must Exist", looks like they do the same job.
XML is:

```
  <rule name="Exists" value="ID" tracktype="General" occurrence="*"/>
  <rule name="Must Exist" value="ID" tracktype="General" occurrence="*" operator="exists"/>
```

Is there any reason for having both?

**Comment by dericed** [comment]
I noted a discrepancy about it when we discusse "Must not exist". I added "Must exist" at that time but left "exists" for reverse comparability. Can drop "exists".

**Comment by JeromeMartinez** [comment]
Compatibility is good to use, but maybe we should avoid a weird display for a beginner (2 lines for the same thing).
As we need to support old policies, XSL should not drop the old fashion. But the UI should have a "upgrade" feature so we upgrade policies to the new style when we load them. Not doable quickly so for later, let's keep it as it right now.
