### ISSUE TITLE
"Create New Policy From File"

### ISSUE THREAD

**Issue by JeromeMartinez** [MediaArea/MediaConch_SourceCode#458]
https://twitter.com/dericed/status/793562904276692997

Eddy Colloton
Potentially stupid question: is there a way to give @MediaConch a video file or MediaInfo report to base a policy on? A "template file?"

Dinah Handel
@EddyColloton @MediaConch not a stupid question!!!! Actually, a very good useful question, the answer to which may be helpful to others!

Jérôme Martinez
@DinahHandel @EddyColloton @dericed  how should we display it for having the feature more visible? At the top of the page? elsewhere?

Dave Rice
‏@JeromeM78 @DinahHandel @EddyColloton Could be on the policy page, "Create New Policy" / "Create New Policy From File".

Eddy Colloton
@dericed @JeromeM78 @DinahHandel yeah I agree w Dave - having it on the Policies page w Import a Policy + Create a Policy could be helpful

**Comment by ablwr** [comment]
This was reported after the Tate workshop in this ticket: https://github.com/MediaArea/MediaConch_SourceCode/issues/357

**Comment by JeromeMartinez** [comment]
oops...
