### ISSUE TITLE
Update Homebrew

### ISSUE THREAD

**Issue by ablwr** [MediaArea/MediaConch_SourceCode#463]
Latest Homebrew MediaConch seems to be 16.04. Time for a version bump to 16.10?

**Comment by JeromeMartinez** [comment]
For the moment it is not in our build process, on our todo list.

**Comment by g-maxime** [comment]
MediaConch 16.10 just validated by Homebrew team: https://github.com/Homebrew/homebrew-core/blob/c7b3755dcfd2bdcb8d0e2dc81fcd7e4b1d19a58e/Formula/mediaconch.rb

Try: `brew update && brew upgrade`

**Comment by ablwr** [comment]
Oh yes!  👍
