### ISSUE TITLE
Brew update on Mac: GUI / CL conflicts

### ISSUE THREAD

**Issue by verwinv** [MediaArea/MediaConch_SourceCode#473]
Is it possible that using Homebrew you have to choose to install either the CL or the GUI version? 

I tried installing MediaConch via the 
`brew tap caskroom/cask && brew cask install mediaconch-app`
command, which seemed to cause all sorts of trouble.

**Comment by dericed** [comment]
Can you provide your output? Your command works for me.

**Comment by verwinv** [comment]
Worked like a charm this time around. Now urged 
'To re-install mediaconch-app, run:
  brew cask reinstall mediaconch-app'
which worked just fine. 
Thanks for the speedy response.
