### ISSUE TITLE
Enable GUI version updates from within the interface

### ISSUE THREAD

**Issue by verwinv** [MediaArea/MediaConch_SourceCode#474]
Would it be possible, e.g. via the About MediaConch page, to show what version the user is on and let them auto-update? (I'm using a Mac, not sure how that process works on other systems)

**Comment by ablwr** [comment]
+1

**Comment by JeromeMartinez** [comment]
The About MediaConch page already contains the version number (third line), including info about when you use a snapshot version. Not enough?

Auto-update: we have different plans:
- Linux: a repository in order to use the standard Linux method for updates
- Mac: Usage of Mac App Store in order to use Mac App Store updater
- Windows: to be decided.

Is Mac App Store version OK for you?

**Comment by JeromeMartinez** [comment]
@verwinv looks like you use Brew, isn't Brew doing updates automatically? cc @dericed

**Comment by verwinv** [comment]
@jeromemartinez 
- you're completely right about the version number! sorry I overlooked that.
- the latest version I installed I downloaded manually from your website. Brew will do an update if you ask it to ('brew upgrade mediaconch'?) but as a user I currently have no way of knowing when a new version is available

**Comment by JeromeMartinez** [comment]
For Brew, I am reluctant to do something "against" the "standard" Brew method (they decide not to warn there is a new version?).
Else is it OK if you use Mac App Store version instead of Brew version for having automatic updates on Mac?

**Comment by verwinv** [comment]
Sure! Sounds like a reasonable solution. Thanks!

**Comment by JeromeMartinez** [comment]
Just to be clear: an auto-update is doable, this is just more work especially for all platforms.
Our short-term plans is to use mechanisms provided by the OS (or repository managers like Brew).
For Windows, we could first do as for MediaInfo (check if there is a new version, popup with info and link for downloading) in a first shot, and in the future we could spend more time, if relevant, for a complete auto-update like in Firefox.

**Comment by verwinv** [comment]
Understood - and agreed that this could be done in a later stage
