### ISSUE TITLE
"non-free" package on Ubuntu

### ISSUE THREAD

**Issue by verwinv** [MediaArea/MediaConch_SourceCode#475]
Hi, when installing MediaConch on Ubuntu 16.04 LT (the package downloaded from the website) and opening the package, the software description includes a "non-free" tag. Do you know why this is?

**Comment by GuillaumeRoques** [comment]
Hi Erwin
No that's weird, we'll take a look on that.

**Comment by JeromeMartinez** [comment]
the text is:

> this software comes from a 3rd party and may contain non-free components.

I think that the important word is "may": as they can not verify that the package is a free software, they flag by default "non-free" for all 3rd party packages, and we can do nothing against that.

Checking the 16.10 software center with the MediaConch package provided through Ubuntu repository, it does not contain this flag.

From my point of view, this is a non-issue, i.e. this is a default flag for packages you install outside of the Ubuntu public repository and there is no possibility to change it. Do you have an example of free software installed the same way which does not have this flag?

**Comment by verwinv** [comment]
ok, that's clear. I was on an older Ubuntu version, so the Software Center didn't yet have MediaConch available. thanks for the feedback!

**Comment by JeromeMartinez** [comment]
> I was on an older Ubuntu version, so the Software Center didn't yet have MediaConch available

Right.
For checking non-free vs free on 16.04, you need to use the command line, apt-get search mediaconch-gui; the one available is in the "Universe" repository = Community-maintained free and open-source software (source: [The four main repositories](https://help.ubuntu.com/community/Repositories/Ubuntu#The_Four_Main_Repositories))
