### ISSUE TITLE
Naming-typo in buildenv09/Read_me.txt: "src09*.zip" => "CDB_src09*.zip"

### ISSUE THREAD

**Issue by pjotrek-b** [MediaArea/MediaConch_SourceCode#490]
Currently verifying PREFORMA compile/build on fresh 16.04 (64bit) ISO install.
Don't know where to find the source for the "Read_me.txt", so I'm posting it as an issue here.

In "buildenv09/Read_me.txt", it says:
> Download and unzip the src09*.zip

To avoid confusion it might be better to change it to:
> Download and unzip the CDP_src09*.zip

**Comment by g-maxime** [comment]
Solved in latest core distribution packages release
