### ISSUE TITLE
CDP_src: Read_me lacks reference to subdirectories

### ISSUE THREAD

**Issue by pjotrek-b** [MediaArea/MediaConch_SourceCode#491]
In the "Read_me.txt" (buildenv09, CDP_src09) it says:
> Download and unzip the src09*.zip. Enter the new directory created.
> To build the CLI, type:
> ./CLI_compile.sh

But the "new directory created" contains 2 subfolders for each implemenation:
  * MediaConch-Implementation
  * MediaConch-Policy

Therefore it might be nice to add the following:
> Download and unzip the src09*.zip. Enter the new directory created.
> You will see 2 subdirectories for the Implementation- and Policy-Checker:
>  * MediaConch-Implementation
>  * MediaConch-Policy
>
> Inside these subfolders, the following commands are used to build the binaries:
> 
> To build the CLI, type:
> ./CLI_compile.sh
> [...]

**Comment by JeromeMartinez** [comment]
thanks. this is due changes in the requested deliverable, Maxime will fix that when he comes back to office.

**Comment by pjotrek-b** [comment]
Where would I find the "Read_me.txt" source?
So I could try to send you a pull request in the future ;)

**Comment by g-maxime** [comment]
Fixed in latest release.

The CDP related scripts and txt aren't published for now.
