### ISSUE TITLE
when -d is used, force -fx

### ISSUE THREAD

**Issue by dericed** [MediaArea/MediaConch_SourceCode#537]
regression

```
mediaconch -d really_excited_to_test_my_custom_display.xsl -p policy.xml dramatic.mov
```

```
If a display is used, no other output format can be used
```

:-/

**Comment by JeromeMartinez** [comment]
regression? What was the previous behavior?
From my point of view it is the expected behavior: display option is the output format config.

**Comment by dericed** [comment]
iirc before the user could create their own display and call it with `-d`. Now there is a warning, so only internal displays are possible to use.

**Comment by JeromeMartinez** [comment]
workaround: add " -fx" to the command line.

**Comment by dericed** [comment]
updated the title.
