### ISSUE TITLE
crash on garbarge url

### ISSUE THREAD

**Issue by dericed** [MediaArea/MediaConch_SourceCode#56]
If I open the GUI on a mac, select to do a policy test on an online file and enter garbarge for a url, and run. I get a crash.

If I leave url empty, no crash, but also no error.

**Comment by JeromeMartinez** [comment]
Corrected during the MediaArea/MediaTrace XML changes (now alwaus with "media" element), no more crash but non existant file is marked as "valid" (because there is no "failed" test), we may need to discuss about what to show when a file does not exist.
