### ISSUE TITLE
jstree of mediainfo, default display to 2 levels

### ISSUE THREAD

**Issue by dericed** [MediaArea/MediaConch_SourceCode#57]
in the ui, if I display the mediainfo report in jstree, it defaults to opening the top level nodes, so I can see the tracks. can we default here to all levels open. I think this makes it look like the more familiar mediainfo report we know.

**Comment by GuillaumeRoques** [comment]
Done : https://github.com/MediaArea/MediaConch_SourceCode/commit/83231ab548fd832448f34552689e46d166703556
You can test it with today snapshots.
