### ISSUE TITLE
failed implementation check using CLI only

### ISSUE THREAD

**Issue by kieranjol** [MediaArea/MediaConch_SourceCode#611]
Hi,

So this seems like it's definitely an issue with my environment on a particular workstation and I'd like to know what might be causing it. 
I have a lot of MKV files that fail the MKV implementation check on the CLI, but they pass the implementation check in the GUI of the latest snapshot. I'm tried 17.06 via homebrew and the latest snapshot as well. I installed mediaconch on a different workstation on CLI and GUI and the files pass the implementation check fine. So it seems that my particular environment is a bit messed up, perhaps the XML tools? Is there something else that I can check in my environment that could be causing this?
This is the error:
```
 -- EBML-ELEMENT-VALID-PARENT
 --    [fail:Colour is not a valid Parent Element of 15B7.]
 --     [/Segment[1]/Tracks[1]/TrackEntry[1]/Video[1]/Colour[1]/15B7[1] at bytes offset of 475]
 --    [fail:Colour is not a valid Parent Element of 15B8.]
 --     [/Segment[1]/Tracks[1]/TrackEntry[1]/Video[1]/Colour[1]/15B8[1] at bytes offset of 479]
```
and the full report from the CLI:
https://gist.github.com/kieranjol/8c90289b0cd18f798f0275e0c6632656

**Comment by JeromeMartinez** [comment]
It may be due to the file analysis part is from an older version of MediaConch, and the updated tool did not rechecked the file, so the new fields are still unknown in the trace.
Can you test with ` --force` option?

**Comment by kieranjol** [comment]
AAAAAARG - thanks so much Jerome, that fixed it!

Cheers,

-Kieran.

**Comment by JeromeMartinez** [comment]
That demonstrates that we need to have a better management of old analysis.
