### ISSUE TITLE
Possible mediaconch false positive due to relocated Track headers in MKV?

### ISSUE THREAD

**Issue by kieranjol** [MediaArea/MediaConch_SourceCode#612]
Hi all,

I don't fully understand this issue, so I'll link/copy paste to @mbunkus at the end.
This file is valid via the mediaconch implementation check: 
https://drive.google.com/open?id=0B80EiSambHhLSnMwQnc1NFZ0Mnc

This next file (https://drive.google.com/file/d/0ByvCvU9YVB09WTNSQ2ZEdXk2YXM/view?usp=sharing) was produced by `mkvpropedit` using 
` --edit track:v1 --set colour-primaries=5 --set colour-range=1 --set colour-matrix=5 --set colour-transfer-characteristics=3`
and Mediaconch declares it invalid.

Seems that it could be a false positive?

It seems the element in question is:
```
<test outcome="fail" reason="Timecode MUST be a Child Element of Cluster but is not present.">
<value name="Cluster" offset="1568" context="/Segment[1]/Cluster[1]" formatid="0x1F43B675">[472989 bytes]</value>
```
Full report here: https://gist.github.com/kieranjol/cd233abae018ceb05c0cd936a1f3371c

And here is thread with @mbunkus's analysis.
https://github.com/mbunkus/mkvtoolnix/issues/2038#issuecomment-320445233

> About changing that file. Well, I can guarantee you that mkvpropedit is not touching any of the clusters. And if you run mkvinfo -v -v mkvpropeditoutput.mkv, you'll see that there is a cluster timecode element in the cluster at 1568:
> 
> |+ Cluster at 1568
> | + Cluster timecode: 0.000s at 1586
> | + SimpleBlock (key, track number 1, 1 frame(s), timecode 0.000s = 00:00:00.000) at 1589
> |  + Frame with size 472960
> One thing that is different is that mkvpropedit had to relocate the track headers (the Tracks element) to the end of the file due to there not being enough space at the front. Of course that Tracks element is now referenced from the Meta Seek element at the start, so any compliant reader should be able to find the Tracks element just fine. But maybe MediaConch has some problems with that? See also this FAQ entry that describes this in more detail.
> 
> So I'm really not sure what MediaConch is complaining about, especially why it's emitting that particular error. You should probably check back with their developers.

**Comment by kieranjol** [comment]
sorry, i hit send too soon, re-editing the first post now.

**Comment by ablwr** [comment]
Thanks @kieranjol!

**Comment by kieranjol** [comment]
Hi Jerome, I tested this in today's snapshot on Ubuntu 16.04 but the file still fails in the same way.
```
MediaConch Command Line Interface 17.06.20170807

mediaconch --force ~/Downloads/mkvpropeditoutput.mkv 
fail! Downloads/mkvpropeditoutput.mkv
 -- EBML-ELEMENT-CONTAINS-MANDATES
 --    [fail:Timecode MUST be a Child Element of Cluster but is not present.]
 --     [/Segment[1]/Cluster[1] at bytes offset of 1568]

```

**Comment by JeromeMartinez** [comment]
did you update `libmediainfo0`?

**Comment by kieranjol** [comment]
No, I'm so sorry. I updated and the file passes. Thanks yet again!!
