### ISSUE TITLE
Need to have a meanigful message if no home dir

### ISSUE THREAD

**Issue by jrwdunham** [MediaArea/MediaConch_SourceCode#634]
I am having issues when I attempt to install the MediaConch CLI v. 16.12 on a Ubuntu 14.04 machine (docker container) using the following commands:

    $ curl https://mediaarea.net/download/binary/libzen0/0.4.34/libzen0_0.4.34-1_amd64.xUbuntu_14.04.deb --output libzen0_0.4.34-1_amd64.xUbuntu_14.04.deb
    $ curl https://mediaarea.net/download/binary/libmediainfo0/0.7.91/libmediainfo0_0.7.91-1_amd64.xUbuntu_14.04.deb --output libmediainfo0_0.7.91-1_amd64.xUbuntu_14.04.deb
    $ curl https://mediaarea.net/download/binary/mediaconch/16.12/mediaconch_16.12-1_amd64.xUbuntu_14.04.deb --output mediaconch_16.12-1_amd64.xUbuntu_14.04.deb
    $ dpkg -i libzen0_0.4.34-1_amd64.xUbuntu_14.04.deb
    $ dpkg -i libmediainfo0_0.7.91-1_amd64.xUbuntu_14.04.deb
    $ dpkg -i mediaconch_16.12-1_amd64.xUbuntu_14.04.deb

To be exact, I am using the Docker file at https://github.com/artefactual/archivematica/blob/4e9e1cc72f38041c1b0428b637a4a0719e1cdfc2/src/MCPClient.Dockerfile.

The issue arises when I attempt to perform an implementation check on an MKV file:

    $ docker-compose exec archivematica-mcp-client mediaconch -mc -fx -iv 5 /var/archivematica/sharedDirectory/mkv-conforms-NYULibraries_MKVFFV1.mkv
    runtime error: element variable
    Variable 'schema' has not been declared.
    runtime error: element variable
    Evaluating global variable  var/param being computed failed
    runtime error: element for-each
    Variable 'lookupschema' has not been declared.
    runtime error: element for-each
    Failed to evaluate the 'select' expression.
    runtime error: element variable
    Variable 'schema' has not been declared.
    runtime error: element variable
    Evaluating global variable  var/param being computed failed
        xmlXPathCompOpEval: parameter error
        xmlXPathCompiledEval: evaluation failed
        xmlXPathCompiledEval: evaluation failed
        xmlXPathCompOpEval: parameter error
        xmlXPathCompiledEval: evaluation failed

I get similar errors when I attempt to install v. 17.12 also.

Any assistance with this would be much appreciated. Thank you.

**Comment by g-maxime** [comment]
MediaConch need to create some files to work properly.
Does those paths are writable by the user that launch MediaConch?
- $HOME/. local/share
- $HOME/. local/share/MediaConch (if exist)

**Comment by jrwdunham** [comment]
Thanks @g-maxime. You were right. This seems to have been fixed by creating the archivematica user's home directory, in this case by adding the `-m` flag so that the relevant line in the Dockerfile looks like `useradd -m --uid 333 --gid 333 --system archivematica`. This can be closed imo.

**Comment by JeromeMartinez** [comment]
I let it open for reminding us to have a better message in case of such issue.

**Comment by JeromeMartinez** [comment]
[Better message implemented](https://github.com/MediaArea/MediaConch_SourceCode/pull/639), in [snapshots](https://mediaarea.net/download/snapshots/binary/mediaconch/).
