### ISSUE TITLE
version numbers missing on macOS

### ISSUE THREAD

**Issue by core-code** [MediaArea/MediaConch_SourceCode#654]
i've downloaded Version '18.03.2' for Mac but when selecting it in the Finder and using 'Get Info' it doesn't show any Version-number at all. i guess the **CFBundleVersion** and **CFBundleShortVersionString** entries in your **Info.plist** file are missing.
all apps on macOS are supposed to contain valid version information.

**Comment by JeromeMartinez** [comment]
hum... [we have them](https://github.com/MediaArea/MediaConch_SourceCode/blob/a0b4f3c6951336138dd5b74115e633e97e930849/Project/Mac/Info.plist#L21-L24)...

**Comment by core-code** [comment]
hey jerome, thanks for your prompt answer.

nice to know that this is supposed to work in principle, but if you actually download 18.03.2:
https://mediaarea.net/download/binary/mediaconch-gui/18.03.2/MediaConch_GUI_18.03.2_Mac.dmg
then you'll see it doesn't contain any of the stuff you've linked:

<img width="455" alt="screenshot 2018-10-02 at 00 52 51" src="https://user-images.githubusercontent.com/1261954/46320222-a61a8400-c5dd-11e8-8ef7-8dd3cfc807e5.png">

**Comment by JeromeMartinez** [comment]
@core-code please test [this development snapshot](https://mediaarea.net/download/snapshots/binary/mediaconch-gui/20181008/MediaConch_GUI_18.03.2.20181008_Mac.dmg).

**Comment by core-code** [comment]
yes, this one properly has versions

**Comment by JeromeMartinez** [comment]
Fixed by https://github.com/MediaArea/MediaConch_SourceCode/pull/655.

**Comment by core-code** [comment]
thanks!
