### ISSUE TITLE
MediaConch & S3 storage?

### ISSUE THREAD

**Issue by pjotrek-b** [MediaArea/MediaConch_SourceCode#669]
I've used MediaInfo super easily on an S3 (ceph) object based storage to retrieve tech-metadata from several thousand files. Worked like a charm, but now I'm piling up bash+grep+spreadsheet scripts to analyze/sort them... :fearful: :mask: 

So could MediaConch be used to do the same, but then provide policy-filtering and e.g. other stuff by direct access to MediaConch's (SQLite?) database?

Just an idea :grin:

**Comment by JeromeMartinez** [comment]
I expected that the CLI can analyze remote files, the same way it is as with local files.
I don't get the issue.

```
> more .\IsOgg.xml
<?xml version="1.0"?>
<policy type="and" name="Is OGG" license="CC-BY-SA-4.0+">
  <rule name="Is OGG" value="Format" tracktype="General" occurrence="*" operator="=">Ogg</rule>
</policy>

> more .\IsNotOgg.xml
<?xml version="1.0"?>
<policy type="and" name="Is not OGG" license="CC-BY-SA-4.0+">
  <rule name="Is not OGG" value="Format" tracktype="General" occurrence="*" operator="!=">Ogg</rule>
</policy>

> .\MediaConch.exe https://mediaarea.net/temp/Example.ogg -p .\IsOgg.xml
pass! https://mediaarea.net/temp/Example.ogg

> .\MediaConch.exe https://mediaarea.net/temp/Example.ogg -p .\IsNotOgg.xml
fail! https://mediaarea.net/temp/Example.ogg
   --  [fail:Is not OGG]
   --   [fail:Is not OGG]
```

**Comment by pjotrek-b** [comment]
Sorry: It's not an issue. I just didn't know if MediaConch supports S3 (or just MediaInfo).

I take your reply as: "Yes it can!" :smile:
Thank you!
