### ISSUE TITLE
MediaConch binary for Lambda

### ISSUE THREAD

**Issue by flibustier** [MediaArea/MediaConch_SourceCode#675]
Hi!
We are moving our uses of Media Info and Media Conch using AWS Lambda, we discovered the compiled version of media info (like `MediaInfo_CLI_20.03.20200810_Lambda.zip`) but there is no equivalent for MediaConch and we have trouble to compile it using `CLI_Compile.sh`

Is it possible to add the Lambda target for MediaConch ?

Or helping debug with the compilation, I’ve got:
```
bash-4.2# ./CLI_Compile.sh 
Checking for gcc...
Building static library libz.a version 1.2.11 with gcc.
Checking for size_t... Yes.
…
everything got yes
…
config.status: config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands
Done configuring
configure: WARNING: unrecognized options: --without-modules
configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."
Problem while configuring libxslt
```
And the compilation stop here…

I used Amazon linux 2 image with this configuration:
```
FROM amazonlinux:2

RUN yum groupinstall -y 'Development Tools' && yum install -y \
    libcurl-devel \
    libxml2-devel \
    libxslt-devel \
    libevent-devel \
    sqlite-devel \
    jansson-devel
```

Thank you very much for your hard work

**Comment by JeromeMartinez** [comment]
> And the compilation stop here…

We'll check if we can easily reproduce and fix (this is considered a bug, everyone should be able to compile it).

> Is it possible to add the Lambda target for MediaConch ?

First request :). This is doable to automate the build and release the lambda version as with MediaInfo, but as MediaConch has low sponsorship for the moment it is not on the top of our todo-list, no ETA, you may consider [to sponsor the development](https://mediaarea.net/Services) for accelerating the development.

**Comment by flibustier** [comment]
Thank you very much for your answer !
Using last available release (MediaConch_CLI_18.03.2_GNU_FromSource.tar.xz) I end up making it works until this:
```
[a lot of things happened before]
Making all in test
MediaInfoLib compiled
 rm -f mediaconch
rm -rf .libs _libs
rm -f *.o
rm -f ../../../Source/CLI/*.o
rm -f ../../../Source/Common/*.o
test -z "test/simple.sh.log test/filename.sh.log test/test_mk.sh.log test/test_ffv1.sh.log" || rm -f test/simple.sh.log test/filename.sh.log test/test_mk.sh.log test/test_ffv1.sh.log
test -z "test/simple.sh.trs test/filename.sh.trs test/test_mk.sh.trs test/test_ffv1.sh.trs" || rm -f test/simple.sh.trs test/filename.sh.trs test/test_mk.sh.trs test/test_ffv1.sh.trs
test -z "test-suite.log" || rm -f test-suite.log
rm -f *.lo
In file included from ../../../Source/Common/Core.cpp:21:0:
../../../Source/Common/Xslt.h:19:10: fatal error: libxslt/xslt.h: No such file or directory
 #include <libxslt/xslt.h>
          ^~~~~~~~~~~~~~~~
compilation terminated.
make: *** [../../../Source/Common/mediaconch-Core.o] Error 1
make: *** Waiting for unfinished jobs....
Problem while compiling MediaConch (CLI)
```

**Comment by JeromeMartinez** [comment]
> ../../../Source/Common/Xslt.h:19:10: fatal error: libxslt/xslt.h: No such file or directory

This file is in the package, we'll check what is going wrong in the path of source file provided to the compiler (weird, as we use this command for building our deliveries...)

**Comment by flibustier** [comment]
A bit update on this, last problem was solved installing `libxslt-devel` but now compilation fails here (still trying to compile the last release): 
```
../../../../sqlite/.libs/libsqlite3.a(sqlite3.o): In function `unixDlError':
/MediaConch_CLI_GNU_FromSource/sqlite/sqlite3.c:35971: undefined reference to `dlerror'
../../../../sqlite/.libs/libsqlite3.a(sqlite3.o): In function `unixDlClose':
/MediaConch_CLI_GNU_FromSource/sqlite/sqlite3.c:36002: undefined reference to `dlclose'
../../../../sqlite/.libs/libsqlite3.a(sqlite3.o): In function `unixDlSym':
/MediaConch_CLI_GNU_FromSource/sqlite/sqlite3.c:35998: undefined reference to `dlsym'
../../../../sqlite/.libs/libsqlite3.a(sqlite3.o): In function `unixDlOpen':
/MediaConch_CLI_GNU_FromSource/sqlite/sqlite3.c:35957: undefined reference to `dlopen'
/MediaConch_CLI_GNU_FromSource/MediaInfoLib/Project/GNU/Library/.libs/libmediainfo.a(Reader_libcurl.o): In function `MediaInfoLib::Reader_libcurl::Load(ZenLib::Ztring)':
Reader_libcurl.cpp:(.text+0x2ed8): undefined reference to `dlopen'
Reader_libcurl.cpp:(.text+0x2ef9): undefined reference to `dlsym'
Reader_libcurl.cpp:(.text+0x2f19): undefined reference to `dlsym'
Reader_libcurl.cpp:(.text+0x2f3b): undefined reference to `dlsym'
Reader_libcurl.cpp:(.text+0x2f5d): undefined reference to `dlsym'
Reader_libcurl.cpp:(.text+0x2f7f): undefined reference to `dlsym'
/MediaConch_CLI_GNU_FromSource/MediaInfoLib/Project/GNU/Library/.libs/libmediainfo.a(Reader_libcurl.o):Reader_libcurl.cpp:(.text+0x2fa1): more undefined references to `dlsym' follow
/MediaConch_CLI_GNU_FromSource/MediaInfoLib/Project/GNU/Library/.libs/libmediainfo.a(Reader_libcurl.o): In function `MediaInfoLib::Reader_libcurl::Load(ZenLib::Ztring)':
Reader_libcurl.cpp:(.text+0x311f): undefined reference to `dlopen'
Reader_libcurl.cpp:(.text+0x3140): undefined reference to `dlopen'
Reader_libcurl.cpp:(.text+0x3161): undefined reference to `dlopen'
Reader_libcurl.cpp:(.text+0x3182): undefined reference to `dlopen'
Reader_libcurl.cpp:(.text+0x31a3): undefined reference to `dlopen'
collect2: error: ld returned 1 exit status
make: *** [mediaconch] Error 1
Problem while compiling MediaConch (CLI)
```

**Comment by flibustier** [comment]
An update on this, we have successfully build a binary for lambda, here are the step followed:
```dockerfile
FROM amazonlinux:2

RUN yum groupinstall -y 'Development Tools'

RUN yum install -y \
    libcurl-devel \
    libxslt-devel

ENV MEDIAAREA_DIR=/srv/deploy/mediaarea
RUN mkdir -p $MEDIAAREA_DIR
WORKDIR $MEDIAAREA_DIR

ENV LIBS=-ldl

RUN curl https://mediaarea.net/download/binary/mediaconch/18.03.2/MediaConch_CLI_18.03.2_GNU_FromSource.tar.xz -o MediaConch_CLI_GNU.tar.xz && \
    tar xvf MediaConch_CLI_GNU.tar.xz && \
    cd MediaConch_CLI_GNU_FromSource && \
    ./CLI_Compile.sh
```
(binary will be here: `MediaConch_CLI_GNU_FromSource/MediaConch/Project/GNU/CLI/mediaconch`)

`libxslt/xslt.h: No such file or directory` was solved installing `libxslt-devel` on build machine
`undefined reference to `dlopen'`/`undefined reference to `dlsym'`/`dlclose`… was solved using `LIBS=-ldl` in env

This bugs was found trying to `CLI_Compile.sh` with `MediaConch_CLI_18.03.2_GNU_FromSource.tar.xz`

Using last snapshot (`MediaConch_CLI_18.03.2.20200812_GNU_FromSource.tar.xz`), there is trouble with `libxslt`:
`error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."` could be solved going in `libxslt` directory and running `autoreconf -i`
But then there is an error during `configure` after checking for `xml2-config` (seems a parsing error)

Hope all of this could help for people looking to create a Media Conch binary for lambda, if we could open a PR to add the target I could try to help :) 

Thank you for your awesome work 👍

**Comment by JeromeMartinez** [comment]
> An update on this, we have successfully build a binary for lambda, here are the step followed:

Thanks for your report.
for libcurl, true that we don't provide it in the MediaConch "all in one package", so it needs to be installed on the dev machine, and amazonlinux does not have it anymore. We solved that in MediaInfo by statically linkink libcurl, and we need to do same for MediaConch.
for libxslt, it is in the "all in one package" so we don't expect the dev to install it, something to fix.
for `-ldl`, it should not be needed when libcurl is linked statically, something to check on our side

Have fun with MediaConch in a Lambda!

> Hope all of this could help for people looking to create a Media Conch binary for lambda, if we could open a PR to add the target I could try to help :)

Not sure about the usefulness, as we have a specific build system, I let first @g-maxime check issue per issue and see how long it is to automate in our build system.

**Comment by JeromeMartinez** [comment]
MediaConch [snapshots](https://mediaarea.net/download/snapshots/binary/mediaconch/) have now a Lambda flavor.
New, there are [libmediaconch snapshots], also with a Lambda flavor, which can be used directly by e.g. Python (for Python, it is available through [pip install mediaconch](https://pypi.org/project/mediaconch/), also from a Lambda).

So I think we can close this issue now :-).
