### ISSUE TITLE
Support Mix of AND / OR and WHEN operators within a single policy

### ISSUE THREAD

**Issue by jsciame** [MediaArea/MediaConch_SourceCode#676]
Would it be possible within MediaConch to support a mix of AND / OR operators within a single policy as well as the ability to implement when conditionals. I came across this software looking for existing applications that could validate media against specifications using MediaInfo.  MediaConch almost fits the need but I'd be concerned about the balooning number of policies i'd need to create to support my use cases and duplication of values across policies which are for the most part the same but allowing some variations.

As one example,  we need to validate conformance of incoming ProRes MOV content by allowing frame rates of 23.976, 29.97 and 25 and validating scan type (Interlaced or Progressive) based on the frame rate. With my limited understanding of the software, we'd need 5 different policy documents, one for each frame rate and then one for each combination allowed for scan type. I'd like to be able to describe something like:

-AND (MOV) AND (ProRes) AND (23.976 OR 29.97 OR 25) 
-WHEN 29.97 (Interlaced OR Progressive)
-WHEN 25 (Interlaced OR Progressive)
-WHEN 23.976 (Progressive)

We use MediaInfo and custom code today but I'm intrigued by MediaConch's current capabilities.

We allow several different codecs, frame rates, scan type combinations so the number of policies I'd need to create and check an asset against could be in the multiple double digits and if one doesn't return any failures, I'd know that the file is in spec and if none of them matched, I'd need to find the one with the least errors and then return that report.  All doable but curious about efficiencies.

**Comment by JeromeMartinez** [comment]
I don't get the logic behind "WHEN", I understand that it can be implemented with a mix of "AND" and "OR".

In your case, something like (first part only if you want to skip check on non ProRes MOV files):
( General/Format != MPEG-4 OR Video/Format != ProRes ) OR Video/FrameRate = 29.970 OR Video/FrameRate = 25.000 OR (Video/FrameRate = 23.976 AND Video/ScanType = Progressive)

All in a single policy having sub policies and rules. You could also have a master policy and sub policies per format "(is format 1 AND is spec 1) OR (is format 2 AND is spec 2) OR ..."), and you apply this master policy to your files.

You can check the "Austrian Mediathek: Preservation Master (Video)" example on [the list of public examples](https://mediaarea.net/MediaConchOnline/publicPolicies), it contains complex checks like that ("Is it NTSC or PAL?"), the graphical interface permits you to create without much difficulties such policy or we can create the policy for you (but it is [outside of free support](https://mediaarea.net/Services)).

**Comment by jsciame** [comment]
Thanks Jerome! The sub policies and rules is exactly what I was looking for. Thanks for pointing me to that. Testing it out now.

**Comment by dericed** [comment]
Hi @jsciame, this [policy](https://github.com/amiaopensource/vrecord/blob/master/Resources/vrecord_policy_ffv1.xml) may be helpful as it does look for a narrow set of combinations of technical characteristics to confirm that an output is as expected.

**Comment by jsciame** [comment]
Thanks @dericed. I created one that proves out what I was trying to prove out last night. Once @JeromeMartinez pointed out you can do sub policies inside a master policy, that was the golden ticket.  That should limit the number of policies I need to make and runs assets against.   

`<?xml version="1.0"?>
<policy type="and" name="Contribution Spec" license="CC-BY-SA-4.0+">
  <rule name="PCM" value="Format" tracktype="Audio" occurrence="1" operator="=">PCM</rule>
  <rule name="Height" value="Height" tracktype="Video" occurrence="1" operator="=">1080</rule>
  <rule name="Width" value="Width" tracktype="Video" occurrence="1" operator="=">1920</rule>
  <rule name="Chrome Sub Sampling" value="ChromaSubsampling" tracktype="Video" occurrence="1" operator="=">4:2:2</rule>
  <policy type="or" name="Codec" license="CC-BY-SA-4.0+">
    <rule name="JPEG2000" value="Format" tracktype="Video" occurrence="1" operator="=">JPEG 2000</rule>
    <rule name="ProRes" value="Format" tracktype="Video" occurrence="1" operator="=">ProRes</rule>
  </policy>
  <policy type="or" name="Frame Rate" license="CC-BY-SA-4.0+">
    <policy type="and" name="23.98" license="CC-BY-SA-4.0+">
      <rule name="23.98" value="FrameRate" tracktype="Video" occurrence="*" operator="=">23.976</rule>
      <rule name="Scan Type" value="ScanType" tracktype="Video" occurrence="1" operator="=">Progressive</rule>
    </policy>
    <policy type="and" name="29.97" license="CC-BY-SA-4.0+">
      <rule name="29.97" value="FrameRate" tracktype="Video" occurrence="*" operator="=">29.970</rule>
      <policy type="or" name="Scan Type" license="CC-BY-SA-4.0+">
        <rule name="Scan Type_Progressive" value="ScanType" tracktype="Video" occurrence="1" operator="=">Progressive</rule>
        <rule name="Scan Type_Interlaced" value="ScanType" tracktype="Video" occurrence="1" operator="=">Interlaced</rule>
      </policy>
    </policy>
    <policy type="and" name="25" license="CC-BY-SA-4.0+">
      <rule name="25.00" value="FrameRate" tracktype="Video" occurrence="*" operator="=">25.000</rule>
      <policy type="or" name="Scan Type" license="CC-BY-SA-4.0+">
        <rule name="Scan Type_Progressive" value="ScanType" tracktype="Video" occurrence="1" operator="=">Progressive</rule>
        <rule name="Scan Type_Interlaced" value="ScanType" tracktype="Video" occurrence="1" operator="=">Interlaced</rule>
      </policy>
    </policy>
  </policy>
</policy>
`
