### ISSUE TITLE
MediaConch SOM / EOM Checks

### ISSUE THREAD

**Issue by jsciame** [MediaArea/MediaConch_SourceCode#720]
I’m working on some checks for our acquire workflow. One use case I have is that we get metadata that describes the composition of the media. What I want to be able to do is make sure that the SOM & Duration fit within the media’s timecode so we can catch things where the media starts at “01:00:00;00” which the media would not match the metadata. The error here would be that metadata does not match media.

<SOM>
   <SmpteTimeCode>00:00:07;00</SmpteTimeCode>
</SOM>
<Duration>
   <SmpteDuration>
      <SmpteTimeCode>00:00:30;00</SmpteTimeCode>
   </SmpteDuration>
</Duration>

In a self-contained QuickTime file, the two controls, duration and starting timecode, don’t have the controls to do what I need:
 
Other
Count                                    : 192
Count of stream of this kind             : 1
Kind of stream                           : Other
Kind of stream                           : Other
Stream identifier                        : 0
StreamOrder                              : 2
ID                                       : 3
ID                                       : 3
Type                                     : Time code
Format                                   : QuickTime TC
Format                                   : QuickTime TC
Commercial name                          : QuickTime TC
Duration                                 : 3525038
Duration                                 : 58 min 45 s
Duration                                 : 58 min 45 s 38 ms
Duration                                 : 58 min 45 s
Duration                                 : 00:58:45.038
Duration                                 : 00:58:45;01
Duration                                 : 00:58:45.038 (00:58:45;01)
Frame rate                               : 29.970
Frame rate                               : 29.970 (30000/1001) FPS
FrameRate_Num                            : 30000
FrameRate_Den                            : 1001
Time code of first frame                 : 01:00:00;00
TimeCode_DropFrame                       : Yes
Time code, striped                       : Yes
Time code, striped                       : Yes
Language                                 : en
Language                                 : English
Language                                 : English
Language                                 : en
Language                                 : eng
Language                                 : en
Encoded date                             : UTC 2022-02-17 20:54:54
Tagged date                              : UTC 2022-02-17 20:54:54
 
The current rules in MediaConch:
 
```
<rule name="Start TimeCode" occurrence="*" operator="&gt;=" tracktype="Other" value="TimeCode_FirstFrame">00:00:07;[00@29.97fps](mailto:00@29.97fps)</rule>
<rule name="Duration" occurrence="*" operator="&gt;=" tracktype="Other" value="Duration">37.00363333333333</rule>
```
 
What I want to be able to say is:
 
SOM <= TimeCode_FirstFrame
EOM >= TimeCode_LastFrame
 
With duration and >=, is possible that a start timecode could be <= the SOM but much less to the point the duration doesn’t accommodate EOM even though the duration may be >= the duration of the EOM - SOM.

Could this be added based on our discussions?

**Comment by JeromeMartinez** [comment]
Fixed by https://github.com/MediaArea/MediaInfoLib/pull/1510.

Example:
```
<Duration>60.060</Duration>
<FrameRate>29.970</FrameRate>
<FrameCount>1800</FrameCount>
<TimeCode_FirstFrame>01:00:00;00</TimeCode_FirstFrame>
<TimeCode_LastFrame>01:00:59;29</TimeCode_LastFrame>
```
