### ISSUE TITLE
Feature Request: Flag for DF / NDF for Media which does not denote drop frame

### ISSUE THREAD

**Issue by jsciame** [MediaArea/MediaConch_SourceCode#721]
For TTML, specifically SMPTE-TT / IMSC, we get start timecode / end timecode in smpte representation. Currently, SMPTE-TT / IMSC do not specify a drop/non drop as they are media time base. When returning the values for timecode in smpte, can we get a flag added to the mediaconch to allow specification of drop notation to use when calculating the smpte timecode values?

**Comment by JeromeMartinez** [comment]
Implemented with https://github.com/MediaArea/MediaInfoLib/pull/1506.

New option ` --File_DefaultTimeCodeDropFrame=0`, in MediaInfo or MediaConch.
It has an impact on TTML with media time base and when there is a frame rate of 29.97 or 59.94.
- Default or 1: `01:00:00.000 (01:00:00;00)`
- 0: `01:00:00.000 (00:59:56:12)`
