### ISSUE TITLE
Add Frame Rate Num & Frame Rate Den to MediaConch

### ISSUE THREAD

**Issue by jsciame** [MediaArea/MediaConch_SourceCode#726]
Is it possible to add Frame Rate Num and Frame Rate Den to MediaConch?

Frame rate mode                          : CFR
Frame rate mode                          : Constant
Frame rate                               : 23.976
Frame rate                               : 23.976 (24000/1001) FPS
**_FrameRate_Num                            : 24000
FrameRate_Den                            : 1001_**
Frame count                              : 528

They exist in MediaInfo but don't seem to be available as fields in MediaConch. I've tried FrameRate_Den FrameRate_Num & FrameRateDen FrameRate_Num but they don't return any results when run.

  <rule name="Frame Rate Numerator" value="FrameRate_Num" tracktype="Video" occurrence="1" operator="=" xpath="mi:MediaInfo/mi:track[@type='Video'][1]/mi:FrameRate_Num" requested="24000" actual="" outcome="fail"/>
              <rule name="Frame Rate Denominator" value="FrameRate_Den" tracktype="Video" occurrence="1" operator="=" xpath="mi:MediaInfo/mi:track[@type='Video'][1]/mi:FrameRate_Den" requested="1001" actual="" outcome="fail"/>

**Comment by jsciame** [comment]
You can close this one. I updated MediaInfo and GUI to v22.03 and all of the sudden the results are now returning for these values where they were not before. Are there potential conflicts on a machine if you run an older version of the MediaConch GUI?

**Comment by JeromeMartinez** [comment]
> Are there potential conflicts on a machine if you run an older version of the MediaConch GUI?

Fails when a new field is expected but not present, if the policy does not handle empty field as pass.
Sometimes empty fields means "checked but not detected" in new version and "unsupported" in old version and in that case there is no way to differentiate them.
We need to have a policy about upgrades/downgrades, the de facto ones is "downgrades not tested, upgrades best effort with as few changes as possible but not guaranteed that your use case is fine".
