### ISSUE TITLE
Feature Request: Add Severity Level to Policies & Rules

### ISSUE THREAD

**Issue by jsciame** [MediaArea/MediaConch_SourceCode#727]
One of the features we leverage MediaConch for is checking metadata against media. We have an example where we get metadata that denotes items that we can detect from MediaInfo directly i.e. resolution, scan type and we want to check intent versus actual. In some cases, we may not want to fail for a specific rule or policy. 
 
One thought would be to allow a rule or policy that is a “Warning” level versus ones that are hard “Failures”. Would it be possible to add a severity level to the rules and policies with a default of current state which is fail. I think of it as a severity level for the entire policy or for the rule which will allow us to drive workflow. Nice to have vs we can’t process your media because It is completely invalid.
 
This would allow us to catch intent failures without blocking the acquisition and communicate back to distributors to fix the contents of their metadata.
 
The other enabler would also allow us to do things like move to new specs over time while warning that the existing delivery isn’t meeting the new spec but we’ll have a grace period by which we will accept this spec before moving it to a hard failure.

**Comment by JeromeMartinez** [comment]
> This would allow us to catch intent failures without blocking the acquisition and communicate back to distributors to fix the contents of their metadata.

We thought that such case would be handled by 2 policies applied and displayed separately, but it makes sense to have a single display based on a single XML and not difficult on the XML side, but the UI needs some update for an easy configuration of the policy.

**Comment by JeromeMartinez** [comment]
Closed by https://github.com/MediaArea/MediaConch_SourceCode/pull/728.
