### ISSUE TITLE
support -v as a shortcut to --version in CLI

### ISSUE THREAD

**Issue by dericed** [MediaArea/MediaConch_SourceCode#74]
Maybe info on utility and library versions instead of:

```
mediaconch -v
***********************
* 🐚 MediaConch report *
***********************
```

**Comment by tribouille** [comment]
Do the output of 'mediaconch --version' is ok?
Or more information? (Which information?)

**Comment by dericed** [comment]
the output is ok, i'll adjust the ticket title

**Comment by dericed** [comment]
relatedly, we need the --version, -a option in the help doc

**Comment by tribouille** [comment]
I add the --version in the help
-v --> --version
But, there is no "-a" option. (Do you mean "-ha"?)

**Comment by dericed** [comment]
looks good in the 15.12 release
