### ISSUE TITLE
Frame Rate Num / Frame Rate Den Missing from v23.03

### ISSUE THREAD

**Issue by joe-sciame-wm** [MediaArea/MediaConch_SourceCode#749]
Hi Jerome,

Frame Rate Num / Frame Rate Den is missing from v23.03. This was working in previous releases.

When I do a mediainfo -f I get values

```
Frame rate                               : 29.970
Frame rate                               : 29.970 (30000/1001) FPS
FrameRate_Num                            : 30000
FrameRate_Den                            : 1001
```
However, I don't see them in the Mediainfo inside MediaConch GUI and I also don't see it when I run the CLI

```
 <policy name="29.97" type="and" rules_run="4" pass_count="2" info_count="0" warn_count="0" fail_count="2" outcome="fail">
                    <rule name="Scan Type" value="ScanType" tracktype="Video" occurrence="1" operator="=" xpath="mi:MediaInfo/mi:track[@type='Video'][1]/mi:ScanType" outcome="pass"/>
                    <rule name="FrameRate Num" value="FrameRate_Num" tracktype="Video" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='Video'][*]/mi:FrameRate_Num" requested="30000" actual="" outcome="fail"/>
                    <rule name="FrameRate Den" value="FrameRate_Den" tracktype="Video" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='Video'][*]/mi:FrameRate_Den" requested="1001" actual="" outcome="fail"/>
                    <rule name="Scan Order" value="ScanOrder" tracktype="Video" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='Video'][*]/mi:ScanOrder" outcome="pass"/>
                  </policy>
                </policy>
```

Can you take a look?

**Comment by joe-sciame-wm** [comment]
@JeromeMartinez Do you have an update on a resolution to this one?

**Comment by JeromeMartinez** [comment]
> This was working in previous releases.

Which one? Looks like previous MediaConch version was not working too (Num and Den not exported in MediaInfo XML).
Anyway, we see what to change for having it working at least in next versions and in a more secure way.

**Comment by JeromeMartinez** [comment]
@joe-sciame-wm please test [latest snapshots](https://mediaarea.net/download/snapshots/binary/) (mediaconch/mediaconch-gui for Win/macOS/Lambda, libmediainfo0v5 for Linux).

In practice [we provide `FrameRate_Num`/`FrameRate_Den` in default XML output](https://github.com/MediaArea/MediaInfoLib/pull/1735), no need of ` -f` option for forcing their output.

**Comment by joe-sciame-wm** [comment]
@JeromeMartinez Tested and verified that this is working correctly.
