### ISSUE TITLE
MediaConch Extension with Signed Url returning query parameters

### ISSUE THREAD

**Issue by joe-sciame-wm** [MediaArea/MediaConch_SourceCode#752]
When I submit a file to MediaConch using AWS Presign url, I am getting the query parameters passed back in the file extension check. For security reasons I truncated this the response.

Version: MediaConch Command Line Interface 23.03.20230429
OS: Mac OS 12.6.5

`<rule name="Wrapper" value="FileExtension" tracktype="General" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='General'][*]/mi:FileExtension" requested="mxf" actual="mxf?X-Amz-Algorithm=AWS4-HMAC-SHA256&amp;amp;X-Amz-Credential=&amp;amp;X-Amz-Date=20230526T200134Z&amp;amp;X-Amz-Expires=3600&amp;amp;X-Amz-SignedHeaders=host&amp;amp;X-Amz-Security-Token=&amp;amp;X-Amz-Signature=" outcome="fail"/`

**Comment by JeromeMartinez** [comment]
Oops, the query parameters should definitely not be part of the extension field.

**Comment by joe-sciame-wm** [comment]
Thanks @JeromeMartinez. Let me know when you have a build for us to test this fix.

**Comment by JeromeMartinez** [comment]
@joe-sciame-wm I do that tomorrow.
