### ISSUE TITLE
MediaConch / v23 mpeg format check

### ISSUE THREAD

**Issue by mhdezd** [MediaArea/MediaConch_SourceCode#763]
Ever since I updated MediaConch version, the policy i created to check audio files is resulting in errors. All of the files checked show invalid file format. I have used this policy for years now. When i run the same check & policy in 3 other computers with older versions of mediaconch (v18) these pass. The issue seems to be with the last rule in the policy (MPEG audio format check).
I am including the policy here for you to test
<?xml version="1.0"?>
<policy type="and" name="Audio_ArchMaster" license="CC-BY-SA-4.0+">
  <description>Check if archival audio file meets our digitization specifications of: BWav 96/24, PCM</description>
  <rule name="Audio is PCM" value="Format" tracktype="Audio" occurrence="*" operator="=">PCM</rule>
  <rule name="Audio is 96000 Hz" value="SamplingRate" tracktype="Audio" occurrence="*" operator="=">96000</rule>
  <rule name="Audio BitDepth is 24" value="BitDepth" tracktype="Audio" occurrence="*" operator="=">24</rule>
  <rule name="Audio is Wave file" value="Format" tracktype="General" occurrence="*" operator="=">Wave</rule>
  <rule name="Not MPEG" value="Format" tracktype="Audio" occurrence="*" operator="!=">MPEG Audio</rule>
</policy>

**Comment by JeromeMartinez** [comment]
> I am including the policy here for you to test

Not included ;-).

**Comment by mhdezd** [comment]
<?xml version="1.0"?>
<policy type="and" name="Audio_ArchMaster" license="CC-BY-SA-4.0+">
  <description>Check if archival audio file meets our digitization specifications of: BWav 96/24, PCM</description>
  <rule name="Audio is PCM" value="Format" tracktype="Audio" occurrence="*" operator="=">PCM</rule>
  <rule name="Audio is 96000 Hz" value="SamplingRate" tracktype="Audio" occurrence="*" operator="=">96000</rule>
  <rule name="Audio BitDepth is 24" value="BitDepth" tracktype="Audio" occurrence="*" operator="=">24</rule>
  <rule name="Audio is Wave file" value="Format" tracktype="General" occurrence="*" operator="=">Wave</rule>
  <rule name="Not MPEG" value="Format" tracktype="Audio" occurrence="*" operator="!=">MPEG Audio</rule>
</policy>

**Comment by mhdezd** [comment]
[BHL_Audio_ArchMaster.txt](https://github.com/MediaArea/MediaConch_SourceCode/files/12623551/BHL_Audio_ArchMaster.txt)
I couldnt upload the xml so here is a txt version.
