### ISSUE TITLE
Feature: Tolerance on Range values for timecodes

### ISSUE THREAD

**Issue by joe-sciame-wm** [MediaArea/MediaConch_SourceCode#775]
Hi @JeromeMartinez 
We have a use case where we are checking to make sure that timecodes are within a specific range in side car caption and subtitle files.

Time code of first frame                 : 01:00:00;04
Time code of last frame                  : 01:11:21;20

We are seeing issues where assets are right at the edge and the <= => operations cause a failure due to the fact that the value might be 01:11:21;19 that we are looking for.

End Timecode: Expected: TimeCode_LastFrame <= '01:11:21;19', Actual: '01:11:21;20'

We were thinking about adding a tolerance that gives us some wiggle room. At the moment, we are thinking we could do this ourselves in the dynamic policy generation by modifying the XML policy to first and last frame to include that tolerance.

However, curious if this would be a useful feature in general to have a tolerance feature when doing range checks like the one against timecode where you say, its good if its within x tolerance whether that be frames, seconds, etc.

The benefit of the tolerance is that the policy could retain the original values but then maybe return something that indicates it passed because of tolerance. Not sure exactly how to represent that. If we overwrite the policy we lose the original values that we requested so we really can't differentiate with the report that it was passed b/c it was in or passed b/c it wasn't in but was ok due to tolerance.

**Comment by JeromeMartinez** [comment]
> The benefit of the tolerance is that the policy could retain the original values but then maybe return something that indicates it passed because of tolerance.

If I understand correctly, this is the idea behind the "level" of the rule.
What about implementing your tolerance with:
```
  <rule name="Strong error" value="TimeCode_LastFrame" tracktype="Other" occurrence="*" operator="&lt;=" level="info">01:11:21;20</rule>
  <rule name="Tolerance info" value="TimeCode_LastFrame" tracktype="Other" occurrence="*" operator="&lt;=" level="error">01:11:21;19</rule>
```

So if 01:11:21;20 you have no error but still the 01:11:21;20 value in the report due to the info rule.

Or what do I miss?

**Comment by joe-sciame-wm** [comment]
Yes, this would work ok. We'll go ahead and implement this.
