### ISSUE TITLE
File fails MediaInfo rule in MediaConch Policy but is correct in MediaInfo report

### ISSUE THREAD

**Issue by bravoalphatango** [MediaArea/MediaConch_SourceCode#790]
Unsure if this is a MediaConch issue or vrecord, but I am using vrecord (v20241018) to capture tape transfers. When the files are finalizing vrecord says they pass the policy check for FFV1 video (they are MKV/FFV1 files). However, when I run validation checks with MediaConch these same files fail the MediaInfo rule (related to 24 slice count) [within our policy](https://www.dropbox.com/scl/fi/tdcz3ul4n31fovzrmnqkv/2024_video_PM_111224.xml?rlkey=ag3lfw4uyumjkslplodczx5yo&st=17lq2b8m&dl=0), but when I look at the file in MediaInfo the slice count is correct. 

Here is a [sample file and all of the logs](https://www.dropbox.com/scl/fo/1589gy3euo1jf4pf9tqb4/ACuMcHCUrWByLeTzqhGJ3DM?rlkey=shc8b2mdy1yk5azikxlr15ve0&st=yu8g0no0&dl=0) that were generated.

**Comment by JeromeMartinez** [comment]
[Latest snapshots](https://mediaarea.net/download/snapshots/binary/) have the fix (MediaInfo for Windows and macOS, MediaInfoLib for Linux).
You need to use ` --force` on files you already analyzed (du to the cache having the result of the buggy version).
